### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Todgins** [collincusce/redditbots#4]
Hi, am having an issue installing the requirements.

```
pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement apt-xapian-index==0.45 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for apt-xapian-index==0.45 (from -r requirements.txt (line 1))
```

**Comment by Todgins** [comment]
Summary of the packages that wouldn't install from requirements.txt

apt-xapian-index==0.45 //from versions: none
Cheetah==2.4.4 //ERROR: Command errored out with exit status 1: python setup.py egg_info
cloud-init==0.7.5 //from versions: none
configobj==4.7.2 //ERROR: Command errored out with exit status 1: python setup.py egg_info
Landscape-Client==14.12 //from versions: none
PAM==0.4.2 //0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.2.0)
pycurl==7.19.3 //ERROR: Command errored out with exit status 1: python setup.py egg_info
python-apt===0.9.3.5ubuntu3 //from versions: 0.0.0, 0.7.8
python-debian===0.1.21-nmu2ubuntu2 //from versions: 0.1.21-nmu2, 0.1.16, 0.1.21, 0.1.23, 0.1.28, 0.1.30, 0.1.31, 0.1.32, 0.1.33, 0.1.34, 0.1.35, 0.1.36, 0.1.37, 0.1.38, 0.1.39, 0.1.40, 0.1.42, 0.1.43
Twisted-Core==13.2.0 //from versions: none
Twisted-Names==13.2.0 //from versions: none
Twisted-Web==13.2.0 //from versions: none

(Small imgur with the terminal message for apt-xapian-index, cheetah and PAM = https://imgur.com/a/k3PZ628 )

**Comment by collincusce** [comment]
Check your operating system. Does it match what I built it on? I'm not supporting this project. I suggest you fork it.
